# Generated by Django 6.0.3 on 2026-03-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('town', models.CharField(blank=True, max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('service', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('tailoring', 'Tailoring'), ('mechanics', 'Mechanics'), ('photography', 'Photography'), ('carpentry', 'Carpentry'), ('catering', 'Catering'), ('cleaning', 'Cleaning'), ('phone-repair', 'Phone Repair'), ('other', 'Other')], default='other', max_length=50)),
                ('region', models.CharField(choices=[('bono', 'Bono Region'), ('bono-east', 'Bono East Region')], max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-verified', 'name'],
            },
        ),
    ]
