# Generated by Django 6.0.3 on 2026-03-05 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='providers/'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='category',
            field=models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('tailoring', 'Tailoring'), ('mechanics', 'Mechanics'), ('photography', 'Photography'), ('carpentry', 'Carpentry'), ('catering', 'Catering'), ('cleaning', 'Cleaning'), ('phone-repair', 'Phone Repair'), ('design', 'Graphic Design'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='region',
            field=models.CharField(choices=[('bono', 'Bono Region'), ('bono-east', 'Bono East Region')], default='bono', max_length=50),
        ),
    ]
